extends SceneTree
var failures:=0
func _initialize() -> void: run.call_deferred()
func check(ok: bool, message: String) -> void:
	if not ok: failures+=1;push_error(message)
func run() -> void:
	create_timer(50).timeout.connect(func():push_error("Graphics test timed out");quit(1))
	var settings:=root.get_node("GameSettings")
	var path:=OS.get_environment("TEMP").path_join("graphics_settings_%d.cfg"%OS.get_process_id())
	settings._settings_file=path
	settings.load_settings(path)
	check(settings.render_scale==100 and settings.shadow_quality==3 and settings.bloom_enabled and settings.fps_limit==0 and settings.vsync_enabled,"Missing preferences retain visual defaults")
	var first=load("res://scenes/ui/settings_menu.tscn").instantiate()
	var second=load("res://scenes/ui/settings_menu.tscn").instantiate()
	root.add_child(first);root.add_child(second)
	check(first.render_scale_dropdown.item_count==3 and first.fps_limit_dropdown.item_count==4,"Requested menu options")
	paused=true
	first.render_scale_dropdown.select(0);first.shadow_quality_dropdown.select(0)
	first.bloom_dropdown.select(0);first.fps_limit_dropdown.select(1);first.vsync_dropdown.select(0)
	first.render_scale_dropdown.item_selected.emit(0)
	check(root.scaling_3d_scale==.5 and Engine.max_fps==60,"Viewport scale and FPS cap apply while paused")
	check(second.render_scale_dropdown.selected==0 and second.shadow_quality_dropdown.selected==0 and second.bloom_dropdown.selected==0 and second.fps_limit_dropdown.selected==1 and second.vsync_dropdown.selected==0,"Both menus synchronize all graphics controls")
	var saved:=ConfigFile.new();check(saved.load(path)==OK and saved.get_value("graphics","render_scale")==50 and not saved.get_value("graphics","vsync_enabled"),"UI choices persist")
	paused=false
	var world:=Node3D.new()
	var sun:=DirectionalLight3D.new();sun.name="Sun";sun.shadow_enabled=true;sun.directional_shadow_max_distance=300;world.add_child(sun)
	var moon:=DirectionalLight3D.new();moon.name="Moon";moon.shadow_enabled=true;moon.directional_shadow_max_distance=300;world.add_child(moon)
	var lamp:=OmniLight3D.new();lamp.shadow_enabled=true;world.add_child(lamp)
	var unshadowed:=OmniLight3D.new();world.add_child(unshadowed)
	var environment:=WorldEnvironment.new();environment.name="Daylight";environment.environment=Environment.new();world.add_child(environment)
	var clock=load("res://scripts/day_night_cycle.gd").new();clock.cycle_running=false;world.add_child(clock)
	root.add_child(world);await process_frame;await process_frame
	check(not sun.shadow_enabled and not moon.shadow_enabled and not lamp.shadow_enabled,"Off also applies to newly loaded lights")
	clock.time_of_day=23;clock._update_environment()
	check(not environment.environment.glow_enabled,"Bloom stays off after clock update")
	settings.set_graphics_settings(75,1,true,120,false,false)
	check(root.scaling_3d_scale==.75 and Engine.max_fps==120,"75 percent and 120 FPS applied")
	check(sun.shadow_enabled and sun.directional_shadow_max_distance==80 and not lamp.shadow_enabled,"Low: short directional shadows; no local shadows")
	check(environment.environment.glow_enabled,"Bloom restored immediately")
	settings.set_graphics_settings(100,2,true,30,true,false)
	check(sun.directional_shadow_max_distance==160 and lamp.shadow_enabled and Engine.max_fps==30,"Medium and 30 FPS apply")
	settings.set_graphics_settings(100,3,true,0,true,false)
	check(sun.directional_shadow_max_distance==300 and sun.shadow_enabled and not unshadowed.shadow_enabled,"High restores authored shadows without enabling extras")
	check(root.scaling_3d_scale==1 and Engine.max_fps==0,"Native scale and unlimited restore")
	clock.bloom_intensity=0;clock._update_environment()
	check(not environment.environment.glow_enabled,"Artist zero bloom remains disabled")
	settings.load_settings(path)
	check(root.scaling_3d_scale==.5 and Engine.max_fps==60 and not sun.shadow_enabled,"Saved preferences restore live settings")
	check(settings.set_graphics_settings(63,3,true,0,true,false)==ERR_INVALID_PARAMETER and settings.render_scale==50,"Reject unsupported choices without partial application")
	var invalid:=ConfigFile.new()
	invalid.set_value("graphics","render_scale",NAN);invalid.set_value("graphics","shadow_quality",99)
	invalid.set_value("graphics","fps_limit",-1);invalid.set_value("graphics","bloom_enabled","false");invalid.set_value("graphics","vsync_enabled",0)
	invalid.save(path);settings.load_settings(path)
	check(settings.render_scale==100 and settings.shadow_quality==3 and settings.fps_limit==0 and settings.bloom_enabled and settings.vsync_enabled,"Invalid saved values use defaults")
	print("GRAPHICS_SETTINGS: persistence, paused UI synchronization, scene loading, shadow restoration, clock integration; %d failures"%failures)
	world.free();first.free();second.free();DirAccess.remove_absolute(path);quit(1 if failures else 0)
